# pylint: skip-file
"""Add meals and weeks association

Revision ID: 1a8cb1a65a85
Revises: 9646555085ee
Create Date: 2025-01-19 16:28:00.589065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a8cb1a65a85'
down_revision: Union[str, None] = '9646555085ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'meal_week_association',
        sa.Column('meal_id', sa.UUID(), nullable=False),
        sa.Column('week_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ['meal_id'],
            ['meals.id'],
        ),
        sa.ForeignKeyConstraint(
            ['week_id'],
            ['weeks.id'],
        ),
        sa.PrimaryKeyConstraint('meal_id', 'week_id'),
    )
    op.drop_constraint('weeks_user_id_fkey', 'weeks', type_='foreignkey')
    op.create_foreign_key(None, 'weeks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weeks', type_='foreignkey')  # type: ignore
    op.create_foreign_key('weeks_user_id_fkey', 'weeks', 'weeks', ['user_id'], ['id'])
    op.drop_table('meal_week_association')
    # ### end Alembic commands ###
