"""WEP-25_add_device_fingerprint

Revision ID: 04aa7e4d33b2
Revises: f52e84e3d972
Create Date: 2025-11-11 16:56:09.292996

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '04aa7e4d33b2'
down_revision: Union[str, None] = 'f52e84e3d972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('device_fingerprint', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'device_fingerprint')
    # ### end Alembic commands ###
