"""WEP-14_add_meal_slot

Revision ID: 64d80c422561
Revises: a553090aea54
Create Date: 2025-09-14 14:45:25.606525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64d80c422561'
down_revision: Union[str, None] = 'a553090aea54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'recipes',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'meal_slots',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('week_id', sa.Uuid(), nullable=False),
        sa.Column('day_of_week', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='dayofweek'), nullable=False),
        sa.Column('meal_type', sa.Enum('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK', name='mealtype'), nullable=False),
        sa.Column('recipe_id', sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
        sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('week_id', 'day_of_week', 'meal_type', name='_week_day_meal_uc')
    )
    op.create_index(op.f('ix_meal_slots_week_id'), 'meal_slots', ['week_id'], unique=False)
    op.drop_table('meal_week_association')
    op.drop_table('meals')
    op.alter_column(
        'users',
        'created_at',
           existing_type=postgresql.TIMESTAMP(),
           nullable=False,
    )
    op.alter_column(
        'users',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        'weeks',
        'user_id',
        existing_type=sa.UUID(),
        nullable=False,
    )
    op.add_column('weeks', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('weeks', 'week_start')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weeks', 'name')
    op.add_column(
        'weeks',
        sa.Column('week_start', sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        'weeks',
        'user_id',
        existing_type=sa.UUID(),
        nullable=True,
    )
    op.alter_column(
        'users',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        'users',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.create_table(
        'meal_week_association',
        sa.Column('meal_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('week_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], name='meal_week_association_meal_id_fkey'),
        sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], name='meal_week_association_week_id_fkey'),
        sa.PrimaryKeyConstraint('meal_id', 'week_id', name='meal_week_association_pkey'),
    )
    op.create_table(
        'meals',
        sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name='meals_pkey'),
    )
    op.drop_index(op.f('ix_meal_slots_week_id'), table_name='meal_slots')
    op.drop_table('meal_slots')
    op.drop_table('recipes')
    # ### end Alembic commands ###
