"""WEP-59_add_image_key_to_recipes

Revision ID: a9bb0d35c761
Revises: fa819ba9c0e3
Create Date: 2026-03-29 20:36:45.164695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9bb0d35c761'
down_revision: Union[str, None] = 'fa819ba9c0e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    """
    Add a new nullable 'image_key' column (String) to the 'recipes' table.
    
    This migration updates the database schema to store image identifiers or keys associated with recipe records by adding the 'image_key' column.
    """
    op.add_column('recipes', sa.Column('image_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    """
    Revert the migration by removing the `image_key` column from the `recipes` table.
    
    This downgrade reverses the corresponding upgrade() change by dropping the `image_key` column added to the `recipes` table.
    """
    op.drop_column('recipes', 'image_key')
    # ### end Alembic commands ###
