"""WEP-38_remove_device_fingerprint

Revision ID: ab69f7fc8c02
Revises: 04aa7e4d33b2
Create Date: 2026-01-11 18:23:23.406852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab69f7fc8c02'
down_revision: Union[str, None] = '04aa7e4d33b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'device_fingerprint')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('device_fingerprint', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
