"""WEP-5_update_recipe_model

Revision ID: f52e84e3d972
Revises: 7af49569b980
Create Date: 2025-10-11 21:52:03.506030

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f52e84e3d972'
down_revision: Union[str, None] = '7af49569b980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_slots', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('meal_slots', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_constraint('meal_slots_week_id_fkey', 'meal_slots', type_='foreignkey')
    op.drop_constraint('meal_slots_recipe_id_fkey', 'meal_slots', type_='foreignkey')
    op.create_foreign_key(None, 'meal_slots', 'recipes', ['recipe_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'meal_slots', 'weeks', ['week_id'], ['id'], ondelete='CASCADE')
    op.add_column('recipes', sa.Column('is_public', sa.Boolean(), nullable=False))
    op.add_column('recipes', sa.Column('ingredients', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('recipes', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('recipes', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_constraint('recipes_user_id_fkey', 'recipes', type_='foreignkey')
    op.create_foreign_key(None, 'recipes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('refresh_tokens', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_constraint('refresh_tokens_user_id_fkey', 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('refresh_tokens', 'issued_at')
    op.add_column('weeks', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('weeks', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_constraint('weeks_user_id_fkey', 'weeks', type_='foreignkey')
    op.create_foreign_key(None, 'weeks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weeks', type_='foreignkey')
    op.create_foreign_key('weeks_user_id_fkey', 'weeks', 'users', ['user_id'], ['id'])
    op.drop_column('weeks', 'updated_at')
    op.drop_column('weeks', 'created_at')
    op.add_column('refresh_tokens', sa.Column('issued_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key('refresh_tokens_user_id_fkey', 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.drop_column('refresh_tokens', 'updated_at')
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.create_foreign_key('recipes_user_id_fkey', 'recipes', 'users', ['user_id'], ['id'])
    op.drop_column('recipes', 'updated_at')
    op.drop_column('recipes', 'created_at')
    op.drop_column('recipes', 'ingredients')
    op.drop_column('recipes', 'is_public')
    op.drop_constraint(None, 'meal_slots', type_='foreignkey')
    op.drop_constraint(None, 'meal_slots', type_='foreignkey')
    op.create_foreign_key('meal_slots_recipe_id_fkey', 'meal_slots', 'recipes', ['recipe_id'], ['id'])
    op.create_foreign_key('meal_slots_week_id_fkey', 'meal_slots', 'weeks', ['week_id'], ['id'])
    op.drop_column('meal_slots', 'updated_at')
    op.drop_column('meal_slots', 'created_at')
    # ### end Alembic commands ###
