"""WEP-38_add_steps_and_intgredinets_units

Revision ID: fa819ba9c0e3
Revises: 19ffc920c070
Create Date: 2026-03-22 22:00:40.101930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa819ba9c0e3'
down_revision: Union[str, None] = '19ffc920c070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False,  server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'steps')
    # ### end Alembic commands ###
