name: Frontend unittests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  fe_linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Merge base branch into PR
        if: github.event_name == 'pull_request'
        run: |
          echo "Merging base branch (origin/${{ github.event.pull_request.base.ref }}) into HEAD..."
          git merge "origin/${{ github.event.pull_request.base.ref }}"
          echo "Merge successful."

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install frontend dependencies
        run: |
          make fe_install

      - name: Run fe unittests
        run: |
          make fe_test
