name: Python linters

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        make install
    - name: Analysing the code with linters
      run: |
        make lint
