services:
  nginx:
    image: nginx:latest
    ports:
      - "81:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
#      - frontend
    networks:
      default:
        aliases:
          - app.dev.local
  backend:
    build:
      context: ../../
      dockerfile: qa/docker/app/Dockerfile
    environment:
      - DB_URL=postgresql+asyncpg://wep:wep@db:5432/wep
      - BE_HOST=http://app.dev.local
      - FE_HOST=http://app.dev.local
      - JWT_SECRET=gV64m9aIzFG4qpgVphvQbPQrtAO0nM-7YwwOvu0XPt5KJOjAy4AfgLkqJXYEt
      - JWT_ALGORITHM=HS256
      - JWT_ISSUER=wep-auth
      - JWT_AUDIENCE=wep-api
      - ACCESS_TOKEN_TTL=900
      - REFRESH_TOKEN_TTL=30
      - ADMIN_IDS=[193191236]
      - BOT_TOKEN=your_bot_token
      - TG_API_SITE=https://api.telegram.org
    expose:
      - 8000
    depends_on:
      - db
    healthcheck:
      test: [ "CMD-SHELL", "httpx  http://localhost:8000/ping | grep 200" ]
      interval: 15s
      timeout: 5s
      retries: 5
#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    expose:
#      - "3000"
#    volumes:
#      - ./:/app
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: wep
      POSTGRES_USER: wep
      POSTGRES_PASSWORD: wep
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
